import requests
from requests.auth import HTTPBasicAuth

class WordPressIntegration:
    def __init__(self, site_url, username, password):
        self.site_url = site_url
        self.username = username
        self.password = password
        self.rest_url = f'{self.site_url}/wp-json/wp/v2'

    def authenticate(self):
        """
        Authenticate with the WordPress site using Basic Auth.
        It's recommended to use Application Passwords for better security.
        """
        try:
            response = requests.get(f"{self.rest_url}/users/me", auth=HTTPBasicAuth(self.username, self.password))
            response.raise_for_status()
            print("Authentication successful!")
            return True
        except requests.exceptions.HTTPError as err:
            print(f"Failed to authenticate: {err}")
            return False

    def create_post(self, title, content, status='draft'):
        """
        Create a new post with the provided title and content.
        Status can be 'publish', 'future', 'draft', 'pending', 'private'.
        """
        post_data = {
            'title': title,
            'content': content,
            'status': status
        }

        try:
            response = requests.post(f"{self.rest_url}/posts", json=post_data, auth=HTTPBasicAuth(self.username, self.password))
            response.raise_for_status()
            print("Post created successfully!")
            return response.json()
        except requests.exceptions.HTTPError as err:
            print(f"Failed to create post: {err}")
            return None

    def publish_post(self, post_id):
        """
        Update an existing post's status to 'publish'.
        """
        update_data = {
            'status': 'publish'
        }

        try:
            response = requests.post(f"{self.rest_url}/posts/{post_id}", json=update_data, auth=HTTPBasicAuth(self.username, self.password))
            response.raise_for_status()
            print("Post published successfully!")
            return True
        except requests.exceptions.HTTPError as err:
            print(f"Failed to publish post: {err}")
            return False


# Example Usage
if __name__ == "__main__":
    wp = WordPressIntegration('https://yourwordpresssite.com', 'yourusername', 'yourapplicationpassword')

    # Authenticate with WordPress
    if wp.authenticate():
        # Create a new draft post
        post_details = wp.create_post('Generated Content Idea', '<p>This is an awesome content idea generated by AI.</p>', 'draft')

        if post_details is not None:
            # Optionally, publish the post immediately
            # wp.publish_post(post_details['id'])